server:
  port: 8080
  servlet:
    context-path: /movie-recommendation



spring:
  application:
    name: movie-recommendation
  datasource:
    url: "jdbc:mysql://localhost:3306/movie-recommendation"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

jwt:
  signerKey: "CjyrY242aNdw6Rr3FsqDvvQ5SA0OmggwsNVnG8a3mfNZa5yJ6jYhWNDeH2C2iFhp"